# Generated by Django 5.0.1 on 2024-03-01 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_blog_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='user',
        ),
    ]
